### PR TITLE
Add support for x86-64

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
If you are interested, It would be great if we can transfer this plugin to the asdf-community and enhance the tests, etc. What do you think?

**Comment by nverno** [comment]
Thanks!  This is cool, I didn't know sml added 64-bit support. 

As far as merging to asdf, I tried that with a few plugins a year or two ago, but had troubles trying to support macOS.  Do you know if this works on macOS?

**Comment by imbsky** [comment]
This plug-in has been tested on the latest macOS.

**Comment by nverno** [comment]
Does this fail if the chosen version is less than 110.94, though?

**Comment by imbsky** [comment]
Yes, it fails with an error message.

**Comment by imbsky** [comment]
We are now moving many plugins into community organization so that we can be managed by multiple members instead of one. If you are interested, I would like to invite you here to help manage plugins such as SML. We currently run automated tests on Linux and macOS every week to ensure the health of the plugin.
https://github.com/asdf-community

**Comment by nverno** [comment]
I guess that should probably not fail, and ideally there would be a configuration flag to force 32bit on newer versions

**Comment by imbsky** [comment]
It's better to disable 64 bit support before 110.94 and enable it after "110.94" if possible. macOS Catalina no longer supports 32 bit and will not work unless you enable 64 bit support.

**Comment by nverno** [comment]
Sure, that project looks like a really good idea, especially since people fall in and out of using various plugins.

> It's better to disable 64 bit support before 110.94 and enable it after "110.94" if possible. macOS Catalina no longer supports 32 bit and will not work unless you enable 64 bit support.

Sounds good.  By force 32-bit, I had been thinking something like an extra configuration flag, eg.
`USE_32BIT=1`,  that could be set if user wanted to install 32-bit on v110.94+, but default to 64-bit install.

**Comment by imbsky** [comment]
Invited!

> Sounds good. By force 32-bit, I had been thinking something like an extra configuration flag, eg.
USE_32BIT=1, that could be set if user wanted to install 32-bit on v110.94+, but default to 64-bit install.

Oh, that's great! I think I can implement it soon!

**Pull request merged**
